name: Docker Image CI

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Env
        run: |
          echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/norbert-gemes/webbtest4azure:$IMAGE_TAG --tag ghcr.io/norbert-gemes/webbtest4azure:latest
          docker login ghcr.io -u  norbert-gemes -p ${{secrets.WEBTEST4AZURE}}
          docker push ghcr.io/norbert-gemes/webbtest4azure:$IMAGE_TAG
          docker push ghcr.io/norbert-gemes/webbtest4azure:latest
    
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Test-Web-GN'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_f0c57625d4594323b140348462df91ba }}
          images: 'ghcr.io/norbert-gemes/webbtest4azure:${{ env.IMAGE_TAG }}'
