name: Docker Image CI

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Env
        run: |
          echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/norbert-gemes/webbtest4azure:$IMAGE_TAG
          docker login ghcr.io -u  norbert-gemes -p ${{secrets.WEBTEST4AZURE}}
          docker push ghcr.io/norbert-gemes/webbtest4azure:$IMAGE_TAG

